#pragma once

#include "lvgl.h"

// Generated by scripts/gen_home_app_icons.py - do not edit by hand.
namespace agent_ui::home_app_icons {

extern const lv_image_dsc_t kCodex;
extern const lv_image_dsc_t kPhone;
extern const lv_image_dsc_t kFiles;
extern const lv_image_dsc_t kCamera;
extern const lv_image_dsc_t kSettings;

}  // namespace agent_ui::home_app_icons
