#!/usr/bin/env python3
"""Bake the DanmukuPet Q-drop body into an ESP32 RGB565A8 LVGL asset."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image


def clamp_byte(value: float) -> int:
    return max(0, min(255, round(value)))


def extract_face(reference: Image.Image, body: Image.Image, config: dict) -> Image.Image:
    """Copy the Normal face from the full character reference onto the body.

    The generated body's transparent layer deliberately omits the Face prefab.
    The reference has the intended neutral face at the same canvas coordinates,
    so selecting its dark/pink pixels preserves the project character without
    adding the full Unity face atlas to firmware.
    """

    result = body.copy()
    face = config["anchors"]["faceCenterPixel"]
    center_x = int(round(face["x"]))
    center_y = reference.height - int(round(face["y"]))
    left = max(0, center_x - 190)
    right = min(reference.width, center_x + 190)
    top = max(0, center_y - 85)
    bottom = min(reference.height, center_y + 125)

    reference_pixels = reference.load()
    result_pixels = result.load()
    for y in range(top, bottom):
        for x in range(left, right):
            red, green, blue, source_alpha = reference_pixels[x, y]
            luminance = red * 0.2126 + green * 0.7152 + blue * 0.0722
            dark_alpha = clamp_byte((185.0 - luminance) * 3.2)
            pink_delta = max(red - green, red - blue)
            pink_alpha = clamp_byte((pink_delta - 12.0) * 5.0) if red > 175 else 0
            mask_alpha = min(source_alpha, max(dark_alpha, pink_alpha))
            if mask_alpha == 0:
                continue
            destination = result_pixels[x, y]
            amount = mask_alpha / 255.0
            result_pixels[x, y] = (
                clamp_byte(red * amount + destination[0] * (1.0 - amount)),
                clamp_byte(green * amount + destination[1] * (1.0 - amount)),
                clamp_byte(blue * amount + destination[2] * (1.0 - amount)),
                max(destination[3], mask_alpha),
            )
    return result


def rgb565a8_bytes(image: Image.Image) -> bytes:
    colors = bytearray()
    alpha = bytearray()
    for red, green, blue, opacity in image.getdata():
        value = ((red * 31 // 255) << 11) | ((green * 63 // 255) << 5) | (blue * 31 // 255)
        colors.extend((value & 0xFF, value >> 8))
        alpha.append(opacity)
    return bytes(colors + alpha)


def format_byte_array(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16]) + ",")
    return "\n".join(rows)


def write_asset(output_dir: Path, image: Image.Image) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    data = rgb565a8_bytes(image)
    width, height = image.size
    header = output_dir / "q_drop_texture.h"
    source = output_dir / "q_drop_texture.cc"
    preview = output_dir / "q_drop_preview.png"

    header.write_text(
        """#pragma once

#include \"lvgl.h\"

namespace agent_ui::pet_demo {

extern const lv_image_dsc_t kQDropTexture;

}  // namespace agent_ui::pet_demo
""",
        encoding="utf-8",
        newline="\n",
    )
    source.write_text(
        f"""// Generated by scripts/generate_pet_demo_asset.py from DanmukuPet/Q版小水滴.
#include \"q_drop_texture.h\"

#include <cstdint>

namespace agent_ui::pet_demo {{
namespace {{

alignas(4) const uint8_t kQDropTextureData[] = {{
{format_byte_array(data)}
}};

}}  // namespace

const lv_image_dsc_t kQDropTexture = [] {{
    lv_image_dsc_t descriptor{{}};
    descriptor.header.magic = LV_IMAGE_HEADER_MAGIC;
    descriptor.header.cf = LV_COLOR_FORMAT_RGB565A8;
    descriptor.header.w = {width};
    descriptor.header.h = {height};
    descriptor.header.stride = {width * 2};
    descriptor.data_size = sizeof(kQDropTextureData);
    descriptor.data = kQDropTextureData;
    return descriptor;
}}();

}}  // namespace agent_ui::pet_demo
""",
        encoding="utf-8",
        newline="\n",
    )
    image.save(preview, optimize=True)
    print(f"wrote {source} ({width}x{height}, {len(data)} bytes RGB565A8)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--width", type=int, default=256)
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    config = json.loads((source_dir / "step2_body_config.json").read_text(encoding="utf-8"))
    body = Image.open(source_dir / "step2_body.png").convert("RGBA")
    reference = Image.open(source_dir / "step1_character.png").convert("RGBA")
    if body.size != reference.size:
        raise ValueError("step1_character.png and step2_body.png must share a canvas")

    composed = extract_face(reference, body, config)
    alpha_box = body.getchannel("A").getbbox()
    if alpha_box is None:
        raise ValueError("step2_body.png has no visible pixels")
    margin = 8
    crop_box = (
        max(0, alpha_box[0] - margin),
        max(0, alpha_box[1] - margin),
        min(body.width, alpha_box[2] + margin),
        min(body.height, alpha_box[3] + margin),
    )
    cropped = composed.crop(crop_box)
    height = max(1, round(cropped.height * args.width / cropped.width))
    resized = cropped.resize((args.width, height), Image.Resampling.LANCZOS)
    write_asset(args.output_dir.resolve(), resized)


if __name__ == "__main__":
    main()
