#!/usr/bin/env python3
"""Convert home app icon PNGs (white line art on black) into A8 assets.

Outputs:
  - lv_image_dsc_t C sources (compiled-in fallback): main/.../home/home_app_icons.{h,cc}
  - LVGL ".bin" files for SD-card loading: assets/home_icons/<name>.bin

Usage: python3 scripts/gen_home_app_icons.py
Input:  scripts/icon_src/home_apps/<name>.png
"""

import struct
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
SRC_DIR = REPO / "scripts" / "icon_src" / "home_apps"
OUT_DIR = REPO / "main" / "display" / "agent_ui" / "apps" / "home"
BIN_OUT_DIR = REPO / "assets" / "home_icons"

# On-device location on the SD card (mounted at /sdcard); the renderer loads
# "S:" + this path when a file exists there, otherwise the compiled-in A8.
SD_DEST_DIR = "/sdcard/metalio/home_icons"

CANVAS = 120
GLYPH = 104  # longest side after normalization, leaves even padding in the canvas
ICONS = ["codex", "phone", "files", "camera", "settings"]


def load_alpha(path: Path) -> Image.Image:
    image = Image.open(path)
    if image.mode == "RGBA":
        # Prefer alpha if the source ships transparency; luminance otherwise.
        alpha = image.getchannel("A")
        if alpha.getextrema()[0] < 250:
            gray = alpha
        else:
            gray = image.convert("L")
    else:
        gray = image.convert("L")
    # Tight-crop to the artwork, then square-pad so every glyph is normalized.
    bbox = gray.point(lambda v: 255 if v > 24 else 0).getbbox()
    gray = gray.crop(bbox)
    side = max(gray.size)
    padded = Image.new("L", (side, side), 0)
    padded.paste(gray, ((side - gray.width) // 2, (side - gray.height) // 2))
    scaled = padded.resize((GLYPH, GLYPH), Image.LANCZOS)
    canvas = Image.new("L", (CANVAS, CANVAS), 0)
    canvas.paste(scaled, ((CANVAS - GLYPH) // 2, (CANVAS - GLYPH) // 2))
    return canvas


def format_array(name: str, image: Image.Image) -> str:
    data = list(image.getdata())
    lines = []
    for row in range(0, len(data), 16):
        chunk = data[row : row + 16]
        lines.append(
            "    " + " ".join(f"0x{value:02x}," for value in chunk)
        )
    body = "\n".join(lines)
    return (
        f"alignas(4) static const uint8_t {name}Data[] = {{\n{body}\n}};\n"
    )


def format_bin(image: Image.Image) -> bytes:
    # lv_image_header_t: magic:8, cf:8, flags:16, w:16, h:16, stride:16,
    # reserved:16 (12 bytes, little endian), then the raw A8 plane.
    header = struct.pack(
        "<BBHHHHH", 0x19, 0x0E, 0, CANVAS, CANVAS, CANVAS, 0
    )
    return header + image.tobytes()


def descriptor(name: str) -> str:
    cap = name[0].upper() + name[1:]
    return f"""const lv_image_dsc_t k{cap} = [] {{
    lv_image_dsc_t descriptor{{}};
    descriptor.header.magic = LV_IMAGE_HEADER_MAGIC;
    descriptor.header.cf = LV_COLOR_FORMAT_A8;
    descriptor.header.w = {CANVAS};
    descriptor.header.h = {CANVAS};
    descriptor.header.stride = {CANVAS};
    descriptor.data_size = sizeof({name}Data);
    descriptor.data = {name}Data;
    return descriptor;
}}();
"""


def main() -> None:
    header = [
        "#pragma once",
        "",
        "#include \"lvgl.h\"",
        "",
        "// Generated by scripts/gen_home_app_icons.py - do not edit by hand.",
        "namespace agent_ui::home_app_icons {",
        "",
    ]
    source = [
        "#include \"home_app_icons.h\"",
        "",
        "// Generated by scripts/gen_home_app_icons.py - do not edit by hand.",
        "namespace agent_ui::home_app_icons {",
        "",
    ]
    BIN_OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in ICONS:
        image = load_alpha(SRC_DIR / f"{name}.png")
        cap = name[0].upper() + name[1:]
        header.append(f"extern const lv_image_dsc_t k{cap};")
        source.append(format_array(name, image))
        source.append(descriptor(name))
        (BIN_OUT_DIR / f"{name}.bin").write_bytes(format_bin(image))
    header.append("")
    header.append("}  // namespace agent_ui::home_app_icons")
    source.append("")
    source.append("}  // namespace agent_ui::home_app_icons")
    (OUT_DIR / "home_app_icons.h").write_text("\n".join(header) + "\n")
    (OUT_DIR / "home_app_icons.cc").write_text("\n".join(source) + "\n")
    print(f"wrote {OUT_DIR / 'home_app_icons.h'} and .cc ({len(ICONS)} icons)")
    print(f"wrote {len(ICONS)} SD bins to {BIN_OUT_DIR} (copy to {SD_DEST_DIR}/)")
    print(f"wrote {len(ICONS)} SD bins to {BIN_OUT_DIR} (copy to {SD_DEST_DIR}/)")


if __name__ == "__main__":
    main()
